site_name: Blog d'Arturo
site_url: https://arturocandela.github.io/blog/
site_author: Arturo Candela
site_description: Blog personal sobre tecnologia, desenvolupament de software i aprenentatges tècnics

theme:
  name: material
  language: ca
  palette:
    # Paleta per al mode clar - Tons verds menta/sage
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Canvia a mode fosc
    # Paleta per al mode fosc - Tons verds suaus
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Canvia a mode clar
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/leaf
  features:
    # Navegació
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Cerca
    - search.suggest
    - search.highlight
    - search.share
    # Capçalera
    - header.autohide
    # Contingut
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # TOC
    - toc.follow

plugins:
  - search:
      lang: en
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      post_readtime: true
      post_readtime_words_per_minute: 200
      archive: true
      archive_name: Arxiu
      archive_date_format: MMMM yyyy
      archive_url_format: "arxiu/{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "categoria/{slug}"
      authors: true
      authors_file: "{blog}/.authors.yml"
      pagination: true
      pagination_per_page: 10
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
  - tags

copyright: |
  <a href="https://arturocandela.github.io/blog">Blog d'Arturo Candela</a> © 2026 per <a href="https://github.com/arturocandela">Arturo Candela</a> està llicenciat sota <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> <img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arturocandela
      name: GitHub de Arturo Candela
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arturocandela
      name: LinkedIn de Arturo Candela
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Bàsiques
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      permalink_title: Enllaç a aquesta secció
      toc_depth: 3
  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Directori de sortida per a la build
site_dir: site
