site_name: Blog d'Arturo
site_url: https://arturocandela.github.io/blog/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

copyright: |
  <a href="https://arturocandela.github.io/blog">Blog d'Arturo Candela</a> © 2026 per <a href="https://github.com/arturocandela">Arturo Candela</a> està llicenciat sota <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> <img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arturocandela
      name: GitHub

nav:
  - Inici: index.md
  - Posts:
      - Primer post: posts/2026-02-13-primer-post.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

# Clau perquè isca dins /blog/
site_dir: site/blog
